export { default as IconFacebook } from './icons/IconFacebook.astro'
export { default as IconInstagram } from './icons/IconInstagram.astro'
export { default as IconEmail } from './icons/IconEmail.astro'
export { default as BaseLayout } from './BaseLayout.astro'
export { default as NavigationBar } from './NavigationBar.astro'
export { default as Home } from './Home.astro'
export { default as DynamicPage } from './DynamicPage.astro'
