name: Clone Anchorage

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'websites/68waverley/**'
      - 'websites/livinggracedianella/**'
jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: 'livinggracedianella/website-redesign'
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: '0'

      - name: Push to Anchorage repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.PAT_TOKEN }}
          # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
          repository: 'livinggracedianella/anchorage'
          force: 'true'
